###
GET https://localhost HTTP/1.1

###
GET https://localhost/users/1/games HTTP/1.1


### Relationship
### Add Relationship
POST https://localhost/relationships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MywiSXNSb290IjowLCJpYXQiOjE3NTgxMjY4MDEsImV4cCI6MTc1ODIxMzIwMX0.6zxi_WjMVsC2PjsTBZXKfj8yeVGN0s8vZp17p-Yo8v0

{
	"User1Id": 1,
	"User2Id": 1,
	"Relationship": 1
}
###
POST https://localhost/relationships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MywiSXNSb290IjowLCJpYXQiOjE3NTgxMjY4MDEsImV4cCI6MTc1ODIxMzIwMX0.6zxi_WjMVsC2PjsTBZXKfj8yeVGN0s8vZp17p-Yo8v0

{
	"User1Id": 1,
	"User2Id": 1,
}

### Update Relationship
PUT https://localhost/relationships
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MywiSXNSb290IjowLCJpYXQiOjE3NTgxMjY4MDEsImV4cCI6MTc1ODIxMzIwMX0.6zxi_WjMVsC2PjsTBZXKfj8yeVGN0s8vZp17p-Yo8v0
{
	"User1Id": 1,
	"User2Id": 1,
	"Relationship": 0
}
