@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MywiSXNSb290IjowLCJpYXQiOjE3NTgxMjY4MDEsImV4cCI6MTc1ODIxMzIwMX0.6zxi_WjMVsC2PjsTBZXKfj8yeVGN0s8vZp17p-Yo8v0
@userId = 3
@notme = 2

### add
POST http://localhost:3000/relationships
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "User1Id": {{userId}},
  "User2Id": "1",
  "Relationship": 1
}
###
POST http://localhost:3000/relationships
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "User1Id": {{userId}},
  "User2Id": "a",
  "Relationship": 1
}
###
POST http://localhost:3000/relationships
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "User1Id": {{notme}},
  "User2Id": "1",
  "Relationship": 1
}
